### ISSUE TITLE
Documentation tasks following the v5 release

### ISSUE THREAD

**Issue by ismay** [dhis2/ui#119]
### Done

- [x] [Docs landing page](https://ui.dhis2.nu/) has `root` as the title in several places, I'd expect UI, or something of that nature.
- [x] The [getting started page](https://ui.dhis2.nu/#/getting-started) lists ui-core installation instructions, not ui (done, see #158)
- [x] The getting started page has a polyfills section, under which it just says TODO (done, see https://github.com/dhis2/ui/pull/161)
- [x] Storybook does not show syntax (done, fixed in https://github.com/dhis2/ui/pull/162)
- [x] Post on COP once changelog and blogpost have been finalized (done, see here: https://community.dhis2.org/t/release-post-for-dhis2-ui-version-5/39475)
- [x] The [concepts section](https://ui.dhis2.nu/#/concepts) mentions under construction and alpha version, we should check this and rewrite outdated areas to reflect the current situation (done, see: https://github.com/dhis2/ui/pull/166)
- [x] Publish an article about the v5 release, explaining the move and also explaining the changes as we did in for the [v4 release](https://dhis2.nu/2019/12/ui-core-4/). (done, see here: https://developers.dhis2.org/2020/05/ui-5)

### Ready for review

- [x] [Storybook](https://ui.dhis2.nu/demo): widgets is the only uncapitalized folder in the tree (I know, nitpick), plus the nesting seems off (PR: https://github.com/dhis2/ui/pull/167)
- [x] Add styled-jsx gotcha to UI docs instead of notes (PR here: https://github.com/dhis2/ui/pull/168)
- [x] update the links on developers.dhis2.org (PR: https://github.com/dhis2/dhis2.github.io/pull/34)
- [x] Update the _Component & Helper Libraries_ section on the [Libraries page](https://dhis2.nu/libs/) (move outdated libs to Legacy libraries section below) (assuming this is the same issue as the above, PR: dhis2/dhis2.github.io#34)
- [x] Redirect ui-core.dhis2.nu and ui-widgets.dhis2.nu to ui

### Todo

- [ ] Add a link to ui in the docsite navbar
- [ ] Link to release/migration post from the docs, maybe have a Migration Guide docs page (or something) that links to the blogpost for each major release?
- [ ] Remove unused docsite artifacts([this](https://github.com/dhis2/ui/blob/master/packages/ui/d2.config.js#L6-L10), [this](https://github.com/dhis2/ui/blob/master/packages/icons/d2.config.js#L6-L10), [this](https://github.com/dhis2/ui/blob/master/packages/constants/d2.config.js#L6-L10) and [this](https://github.com/dhis2/ui/blob/master/packages/core/d2.config.js#L6-L10)) (and that config option should probably be specified in the root, where the docsite is actually generated)
- [ ] the Table of Contents links on the API page throws a 404 because there's already a hash router. I think this might be solved the config option that's currently specified in the sub-packages (see above)?

### Later

- [ ] The [API section](https://ui.dhis2.nu/#/api) looks pretty good, though there are some spelling errors, and maybe we could unify the styling more. Some have a description, and a lot don't

**Comment by amcgee** [comment]
For the first point, adding a "name" and "description" to the `d2.docsite` key in `package.json` should do the trick (see [docsite docs](https://cli-utils-docsite.dhis2.nu/#/config).  The description will automatically be displayed on the Getting Started page (currently blank)

Also note: it appears there [several](https://github.com/dhis2/ui/blob/master/packages/ui/d2.config.js#L6-L10) [unused](https://github.com/dhis2/ui/blob/master/packages/icons/d2.config.js#L6-L10) [docsite](https://github.com/dhis2/ui/blob/master/packages/constants/d2.config.js#L6-L10) [artifacts](https://github.com/dhis2/ui/blob/master/packages/core/d2.config.js#L6-L10) left over from the monorepo move which should be removed (and that config option should probably be specified in the root, where the docsite is actually generated)

**Comment by amcgee** [comment]
Note also - the Table of Contents links on the [API page](https://ui.dhis2.nu/#/api) throw a 404 because there's already a hash router.  I think this might be solved the config option that's currently specified in the sub-packages?

**Comment by paschalidi** [comment]
On the third point 
>  The getting started page has a polyfills section, under which it just says TODO

Anyone can drop in ideas of what needs to be described?

**Comment by paschalidi** [comment]
@amcgee could you take a moment and point me to the config you mentioning here 

> I think this might be solved the config option that's currently specified in the sub-packages?

I could have a look at that point as well. Doesnt look much of an effort

**Comment by amcgee** [comment]
> Also note: it appears there [several](https://github.com/dhis2/ui/blob/master/packages/ui/d2.config.js#L6-L10) [unused](https://github.com/dhis2/ui/blob/master/packages/icons/d2.config.js#L6-L10) [docsite](https://github.com/dhis2/ui/blob/master/packages/constants/d2.config.js#L6-L10) [artifacts](https://github.com/dhis2/ui/blob/master/packages/core/d2.config.js#L6-L10) left over from the monorepo move which should be removed (and that config option should probably be specified in the root, where the docsite is actually generated)

**Comment by varl** [comment]
https://jira.dhis2.org/browse/LIBS-55
